temporarily drop mt2 dependency
The version of root we use on travis is missing some Minuit stuff:
fatal error: Minuit2/FCNBase.h: No such file or directory
To be investigated...